desk <number_small>: user.desktop(number_small)
desk show: user.desktop_show()
desk right: user.desktop_next()
desk left: user.desktop_last()
desk last: user.desktop_last_used()
desk new: user.desktop_new()
desk remove: user.desktop_remove()
window move desk <number_small>: user.window_move_desktop(number_small)
window move desk left: user.window_move_desktop_left()
window move desk right: user.window_move_desktop_right()
